curl -X POST http://localhost:8080/api/v1/team -H 'Content-Type: application/json' -d '{"name":"Evil Geniuses"}'
curl -X POST http://localhost:8080/api/v1/team -H 'Content-Type: application/json' -d '{"name":"Newbee"}'
curl -X POST http://localhost:8080/api/v1/team -H 'Content-Type: application/json' -d '{"name":"Team Liquid"}'
curl -X POST http://localhost:8080/api/v1/team -H 'Content-Type: application/json' -d '{"name":"LGD Gaming"}'
curl -X POST http://localhost:8080/api/v1/team -H 'Content-Type: application/json' -d '{"name":"Wings Gaming"}'
curl -X POST http://localhost:8080/api/v1/team -H 'Content-Type: application/json' -d '{"name":"Team Secret"}'
curl -X POST http://localhost:8080/api/v1/team -H 'Content-Type: application/json' -d '{"name":"OG"}'
curl -X POST http://localhost:8080/api/v1/team -H 'Content-Type: application/json' -d '{"name":"SK Telecom T1"}'
curl -X POST http://localhost:8080/api/v1/team -H 'Content-Type: application/json' -d '{"name":"Vici Gaming"}'
curl -X POST http://localhost:8080/api/v1/team -H 'Content-Type: application/json' -d '{"name":"Invictus Gaming"}'
curl -X POST http://localhost:8080/api/v1/team -H 'Content-Type: application/json' -d '{"name":"Virtus.pro"}'
curl -X POST http://localhost:8080/api/v1/team -H 'Content-Type: application/json' -d '{"name":"Natus Vincere"}'
curl -X POST http://localhost:8080/api/v1/team -H 'Content-Type: application/json' -d '{"name":"Digital Chaos"}'
curl -X POST http://localhost:8080/api/v1/team -H 'Content-Type: application/json' -d '{"name":"CDEC Gaming"}'
curl -X POST http://localhost:8080/api/v1/team -H 'Content-Type: application/json' -d '{"name":"SK Gaming"}'
curl -X POST http://localhost:8080/api/v1/team -H 'Content-Type: application/json' -d '{"name":"LGD.Forever Young"}'
curl -X POST http://localhost:8080/api/v1/team -H 'Content-Type: application/json' -d '{"name":"EHOME"}'
curl -X POST http://localhost:8080/api/v1/team -H 'Content-Type: application/json' -d '{"name":"Virtus.pro"}'
curl -X POST http://localhost:8080/api/v1/team -H 'Content-Type: application/json' -d '{"name":"Fnatic"}'
curl -X POST http://localhost:8080/api/v1/team -H 'Content-Type: application/json' -d '{"name":"Samsung Galaxy"}'
curl -X POST http://localhost:8080/api/v1/team -H 'Content-Type: application/json' -d '{"name":"MVP Phoenix"}'
curl -X POST http://localhost:8080/api/v1/team -H 'Content-Type: application/json' -d '{"name":"Astralis"}'
curl -X POST http://localhost:8080/api/v1/team -H 'Content-Type: application/json' -d '{"name":"Alliance"}'
curl -X POST http://localhost:8080/api/v1/team -H 'Content-Type: application/json' -d '{"name":"Ninjas in Pyjamas"}'
curl -X POST http://localhost:8080/api/v1/team -H 'Content-Type: application/json' -d '{"name":"Fnatic"}'